import { Log, initLogger } from "./logger";

initLogger("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJzaHJleWEuc2luZ2gyMDI1QHZpdHN0dWRlbnQuYWMuaW4iLCJleHAiOjE3Nzg5MzAzMzksImlhdCI6MTc3ODkyOTQzOSwiaXNzIjoiQWZmb3JkIE1lZGljYWwgVGVjaG5vbG9naWVzIFByaXZhdGUgTGltaXRlZCIsImp0aSI6ImE5YTdhOWIzLWEwYzUtNGI4Yi04NjQzLTYzZjQ1MTJkMGZlYiIsImxvY2FsZSI6ImVuLUlOIiwibmFtZSI6InNocmV5YSBzaW5naCIsInN1YiI6IjMyODJiNDVkLThmMzUtNDFkZS1iNzVhLTMyNWU1NzE5NTlmNyJ9LCJlbWFpbCI6InNocmV5YS5zaW5naDIwMjVAdml0c3R1ZGVudC5hYy5pbiIsIm5hbWUiOiJzaHJleWEgc2luZ2giLCJyb2xsTm8iOiIyNW1jYjEwMDUiLCJhY2Nlc3NDb2RlIjoiU2ZGdVdnIiwiY2xpZW50SUQiOiIzMjgyYjQ1ZC04ZjM1LTQxZGUtYjc1YS0zMjVlNTcxOTU5ZjciLCJjbGllbnRTZWNyZXQiOiJYTVNLVHJ1cEthUFJ4eHVCIn0.jFtaeJh4plkbVEYDdAvU3E85M8jKP5JA-z6mGJw4Gm8");

async function main() {
  await Log("backend", "info", "middleware", "Logging middleware initialized successfully");
}

main();