import { Log, initLogger } from "./logger";

initLogger("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJzaHJleWEuc2luZ2gyMDI1QHZpdHN0dWRlbnQuYWMuaW4iLCJleHAiOjE3Nzg5Mjg0NzMsImlhdCI6MTc3ODkyNzU3MywiaXNzIjoiQWZmb3JkIE1lZGljYWwgVGVjaG5vbG9naWVzIFByaXZhdGUgTGltaXRlZCIsImp0aSI6ImM0NDE5MGIwLWM4ZjAtNDU5Yy1iZTVlLTdiMjAzZjFlMGQ4NiIsImxvY2FsZSI6ImVuLUlOIiwibmFtZSI6InNocmV5YSBzaW5naCIsInN1YiI6IjMyODJiNDVkLThmMzUtNDFkZS1iNzVhLTMyNWU1NzE5NTlmNyJ9LCJlbWFpbCI6InNocmV5YS5zaW5naDIwMjVAdml0c3R1ZGVudC5hYy5pbiIsIm5hbWUiOiJzaHJleWEgc2luZ2giLCJyb2xsTm8iOiIyNW1jYjEwMDUiLCJhY2Nlc3NDb2RlIjoiU2ZGdVdnIiwiY2xpZW50SUQiOiIzMjgyYjQ1ZC04ZjM1LTQxZGUtYjc1YS0zMjVlNTcxOTU5ZjciLCJjbGllbnRTZWNyZXQiOiJYTVNLVHJ1cEthUFJ4eHVCIn0.dD2RuJ1pqN_nQ23EDDBcmhayykV9QazG86KqxcLFgA8");

async function main() {
  await Log("backend", "info", "middleware", "Logging middleware initialized successfully");
}

main();